# Generated by Django 3.1.2 on 2020-10-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_ua', models.IntegerField(blank=True, null=True)),
                ('sigla_ua', models.TextField(blank=True, null=True)),
                ('nome_ua', models.TextField(blank=True, null=True)),
                ('titular', models.TextField(blank=True, null=True)),
                ('cargo', models.TextField(blank=True, null=True)),
                ('cd_ua_pai', models.TextField(blank=True, null=True)),
                ('cd_ua_basica', models.TextField(blank=True, null=True)),
                ('nome_ua_basica', models.TextField(blank=True, null=True)),
                ('sigla_ua_basica', models.TextField(blank=True, null=True)),
                ('nat_juridica', models.TextField(blank=True, null=True)),
                ('ordem_ua_basica', models.TextField(blank=True, null=True)),
                ('ordem_absoluta', models.TextField(blank=True, null=True)),
                ('ordem_relativa', models.TextField(blank=True, null=True)),
                ('tipo_logradouro', models.TextField(blank=True, null=True)),
                ('nome_logradouro', models.TextField(blank=True, null=True)),
                ('trechamento_cep', models.TextField(blank=True, db_column='trechamento_CEP', null=True)),
                ('nome_logradouro_abreviado', models.TextField(blank=True, null=True)),
                ('nro', models.TextField(blank=True, null=True)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('bairro', models.TextField(blank=True, null=True)),
                ('bairro_abreviado', models.TextField(blank=True, null=True)),
                ('localidade', models.TextField(blank=True, null=True)),
                ('cep', models.TextField(blank=True, db_column='CEP', null=True)),
                ('telefones', models.TextField(blank=True, null=True)),
                ('emails', models.TextField(blank=True, null=True)),
                ('horario_funcionamento', models.TextField(blank=True, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('data_criacao_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Dados',
                'managed': False,
            },
        ),
    ]
